name = "StableHLO"
uuid = "11df7cf1-74a9-4cb7-b537-510301b49c1b"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez+git@bsc.es>"]
version = "0.1.0"

[deps]
MLIR = "bfde9dd4-8f40-4a1e-be09-1475335e1c92"

[compat]
MLIR = "0.1"
